# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5430b529335f59f2d75983e4495ea5a51e17cc57519d27aa742c4f0f1ec11a703b2fb5984330735cb59ea7043f96ea9ee136e4e29d46a84051fc901f3a46d10d

test:
  secret_key_base: 9681f485598de6171742118035fd502478aa367801e6218246208ddf0197bb008496287dc85043a27e0e0f22270bb1eab5cd6c094b2a7acf71bc4dcc95f012aa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
